# permissions for end users to view carbonintensityissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: carbonintensityissuer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: carbon
    app.kubernetes.io/part-of: carbon
    app.kubernetes.io/managed-by: kustomize
  name: carbonintensityissuer-viewer-role
rules:
- apiGroups:
  - core.rekuberate.io
  resources:
  - carbonintensityissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.rekuberate.io
  resources:
  - carbonintensityissuers/status
  verbs:
  - get
