# permissions for end users to edit carbonintensityproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: carbonintensityprovider-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: carbon
    app.kubernetes.io/part-of: carbon
    app.kubernetes.io/managed-by: kustomize
  name: carbonintensityprovider-editor-role
rules:
- apiGroups:
  - core.rekuberate.io
  resources:
  - carbonintensityproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.rekuberate.io
  resources:
  - carbonintensityproviders/status
  verbs:
  - get
