---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.rekuberate.io
  resources:
  - carbonintensityproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.rekuberate.io
  resources:
  - carbonintensityproviders/finalizers
  verbs:
  - update
- apiGroups:
  - core.rekuberate.io
  resources:
  - carbonintensityproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.rekuberate.io
  resources:
  - electricitymaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.rekuberate.io
  resources:
  - simulators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.rekuberate.io
  resources:
  - watttimes
  verbs:
  - get
  - list
  - watch
