# permissions for end users to view watttimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: watttime-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: carbon
    app.kubernetes.io/part-of: carbon
    app.kubernetes.io/managed-by: kustomize
  name: watttime-viewer-role
rules:
- apiGroups:
  - core.rekuberate.io
  resources:
  - watttimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.rekuberate.io
  resources:
  - watttimes/status
  verbs:
  - get
