apiVersion: core.rekuberate.io/v1alpha1
kind: CarbonIntensityIssuer
metadata:
  labels:
    app.kubernetes.io/name: carbonintensityissuer
    app.kubernetes.io/instance: carbonintensityissuer-eu-nl
    app.kubernetes.io/part-of: carbon
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: carbon
  name: carbonintensityissuer-eu-nl
spec:
  forecastRefreshIntervalHours: 12
  liveRefreshIntervalHours: 1
  zone: NL
  providerRef:
    kind: Simulator
    name: simulator-sample